name: Clasificación diaria REMPE

on:
  schedule:
    - cron: '0 3 * * *'  # Todos los días a las 03:00 UTC
  workflow_dispatch:     # Permite lanzarlo manualmente

jobs:
  ejecutar-script:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v3

      - name: Instalar R
        uses: r-lib/actions/setup-r@v2

      - name: Instalar paquetes necesarios
        run: |
          Rscript -e "install.packages(c('DBI', 'RPostgres', 'dplyr', 'stringdist', 'tidyr', 'bit64', 'stringr', 'tm', 'writexl'))"

      - name: Crear archivo .Renviron
        run: |
          echo "PGPASSWORD=${{ secrets.PGPASSWORD }}" >> ~/.Renviron

      - name: Ejecutar script de clasificación
        run: |
          Rscript script_clasifica.R

      - name: Guardar archivo como artefacto
        uses: actions/upload-artifact@v3
        with:
          name: resultado-clasificacion
          path: resultado_clasificacion.csv
