name: Clasificación diaria REMPE

on:
  schedule:
    - cron: '0 3 * * *'  # Todos los días a las 03:00 UTC
  workflow_dispatch:     # Permite lanzarlo manualmente

jobs:
  ejecutar-script:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v3

      - name: Instalar R
        uses: r-lib/actions/setup-r@v2

      - name: Instalar paquetes necesarios
        run: |
          Rscript -e "install.packages(c('DBI', 'RPostgres', 'dplyr', 'stringdist', 'tidyr', 'bit64', 'stringr', 'tm', 'writexl'))"

      - name: Crear archivo .Renviron
        run: |
           echo "PGPASSWORD=${{ secrets.PGPASSWORD }}" >> .Renviron
           echo "PGUSER=${{ secrets.PGUSER }}" >> .Renviron
           echo "PGHOST=${{ secrets.PGHOST }}" >> .Renviron
           echo "PGDBNAME1=${{ secrets.PGDBNAME1 }}" >> .Renviron
           echo "PGDBNAME2=${{ secrets.PGDBNAME2 }}" >> .Renviron
           echo "PGPORT=5432" >> .Renviron

      - name: Ejecutar script de clasificación
        run: |
          Rscript script_clasifica.R

      - name: Commit del archivo resultado
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add resultado_clasificacion.csv
          git commit -m "Auto: resultado actualizado [skip ci]" || echo "Sin cambios"
          git push

